{ ... }:
{
  flake.modules.nixos.system-packages =
    { pkgs, inputs, ... }:
    {
      environment.systemPackages = with pkgs; [
        ananicy-cpp
        ananicy-rules-cachyos
        bc
        bind
        bluetui
        bluez
        brightnessctl
        choose
        cron
        dig
        dust
        fbset
        fd
        file
        gnupg
        gzip
        hydra-check
        inputs.nix-search-tv.packages.x86_64-linux.default
        killall
        libnotify
        libappindicator-gtk3
        lsof
        mediainfo
        mtr
        nix-converter
        nurl
        pciutils
        playerctl
        ripgrep
        rtkit
        sd
        swappy
        traceroute
        tree
        tree-sitter
        udiskie
        unzip
        usbutils
        wget
        whois
        xwayland
        yubico-pam
        yubioath-flutter
        zip
      ];
    };
}
