# SCB_APPID="ascension" scb -- %command%
# This hard sets your GPU to avoid the selection of your integrated graphics by games unintentionally
# MESA_VK_DEVICE_SELECT=list vulkaninfo
SCB_NOSCOPE=1
STEAM_COMPAT_DATA_PATH="/games/SteamLibrary/steamapps/compatdata/ascension"
TZ=EST5EDT
command="$command"
