# SCB_APPID="ascension" scb -- %command%
# This hard sets your GPU to avoid the selection of your integrated graphics by games unintentionally
# MESA_VK_DEVICE_SELECT=list vulkaninfo
SCB_NOSCOPE=1
export STEAM_COMPAT_DATA_PATH="${SCB_GAMES_LOCATION:?ScopeBuddy games location is not configured}/SteamLibrary/steamapps/compatdata/ascension"
export TZ="${SCB_TIMEZONE:?ScopeBuddy timezone is not configured}"
command="gamemoderun $command"
