# SCB_APPID="bnet" scb -- %command%
# This hard sets your GPU to avoid the selection of your integrated graphics by games unintentionally
# MESA_VK_DEVICE_SELECT=list vulkaninfo
SCB_NOSCOPE=1
DRI_PRIME=1002:7550
MESA_VK_DEVICE_SELECT=1002:7550
WINE_SIMULATE_WRITECOPY=1
STEAM_COMPAT_DATA_PATH="/games/SteamLibrary/steamapps/compatdata/battlenet"
# Battle.net breaks with Wayland backend and mangohud as a launcher wrapper sometimes, if so set to 0
PROTON_ENABLE_WAYLAND=0
TZ=EST5EDT
command="$command"
