# SCB_APPID="bnet" scb -- %command%
# This hard sets your GPU to avoid the selection of your integrated graphics by games unintentionally
# MESA_VK_DEVICE_SELECT=list vulkaninfo
SCB_NOSCOPE=1
if [[ -n "${SCB_GPU_DEVICE_ID:-}" ]]; then
  export DRI_PRIME="$SCB_GPU_DEVICE_ID"
  export MESA_VK_DEVICE_SELECT="$SCB_GPU_DEVICE_ID"
fi
export WINE_SIMULATE_WRITECOPY=1
export STEAM_COMPAT_DATA_PATH="${SCB_GAMES_LOCATION:?ScopeBuddy games location is not configured}/SteamLibrary/steamapps/compatdata/battlenet"
export DXVK_HDR=1
export PROTON_ENABLE_HDR=1
export TZ="${SCB_TIMEZONE:?ScopeBuddy timezone is not configured}"
export PROTON_ENABLE_WAYLAND=1
command="gamemoderun $command"
