# SCB_APPID="hots" scb -- %command%
# SCB_NOSCOPE=1
SCB_NOSCOPE=1
export DRI_PRIME=1002:7550
export MESA_VK_DEVICE_SELECT=1002:7550
export WINE_SIMULATE_WRITECOPY=1
export STEAM_COMPAT_DATA_PATH="/games/SteamLibrary/steamapps/compatdata/battlenet"
export DXVK_HDR=1
export PROTON_ENABLE_HDR=1
export TZ=EST5EDT
export PROTON_ENABLE_WAYLAND=0
command="gamemoderun $command"
