{
  pkgs,
  nix-versions,
  inputs,
  ...
}:
{
  home.packages = with pkgs; [
    (pkgs.callPackage ../../modules/programs/scopebuddy.nix { })
    (pkgs.callPackage ../../modules/programs/hyprshutdown.nix { })
    aseprite
    asciinema
    blueman
    cmatrix
    deadlock-mod-manager
    gamescope
    gimp
    github-copilot-cli
    grim
    gvfs
    hyprpicker
    hyprsysteminfo
    inputs.hytale-launcher.packages.${pkgs.stdenv.hostPlatform.system}.default
    file-roller
    kdePackages.okular
    libsecret
    nix-versions.packages.${pkgs.stdenv.hostPlatform.system}.default
    oculante
    pinta
    protontricks
    protonup-rs
    prusa-slicer
    hyprpwcenter
    seahorse
    sgdboop
    slurp
    steam
    streamcontroller
    tenacity
    vulkan-tools
    wl-clipboard
    thunar
    thunar-archive-plugin
    thunar-media-tags-plugin
    thunar-volman
  ];
}
