{ ... }:
{
  flake.modules.nixos.system-packages =
    { pkgs, inputs, ... }:
    {
      environment.systemPackages = with pkgs; [
        ananicy-cpp
        ananicy-rules-cachyos
        bat
        bc
        bind
        bluetui
        bluez
        brightnessctl
        btop
        choose
        cron
        dig
        dust
        fbset
        fd
        file
        git
        gnupg
        gzip
        hypridle
        hyprpolkitagent
        inputs.nix-search-tv.packages.x86_64-linux.default
        just
        killall
        libnotify
        libappindicator-gtk3
        lsd
        lsof
        mediainfo
        pciutils
        playerctl
        pcscliteWithPolkit
        ripgrep
        rtkit
        sd
        swappy
        traceroute
        tree
        tree-sitter
        udiskie
        unzip
        usbutils
        wget
        whois
        xwayland
        yazi
        yubico-pam
        yubioath-flutter
        zip
        zsh
      ];
    };
}
