# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7d11a83f-f93e-4087-80e2-b7b73d03d4ab";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e555c985-fbe3-4ee3-b18e-fc5cb0ce9147".device = "/dev/disk/by-uuid/e555c985-fbe3-4ee3-b18e-fc5cb0ce9147";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AE8A-E059";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7f6dba05-5f7a-4e60-9777-c28b8cd0d880"; }
    ];


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
