{ den, inputs, ... }:
{
  den.aspects.packages.homeManager =
    {
      pkgs,
      ...
    }:
    {
      home.packages = with pkgs; [
        appimage-run
        aseprite
        asciinema
        bitwarden-desktop
        blueman
        cmatrix
        comma
        devenv
        evtest
        ffmpeg
        file-roller
        gh-dash
        gimp
        godot
        godotPackages.export-template
        gpu-screen-recorder
        grim
        gvfs
        home-manager
        hyprpicker
        hyprpwcenter
        hyprshutdown
        hyprsysteminfo
        kdePackages.okular
        kitty-themes
        lazyjj
        libsecret
        inputs.nix-versions.packages.${pkgs.stdenv.hostPlatform.system}.default
        obsidian
        oculante
        pinta
        prusa-slicer
        redact
        seahorse
        slurp
        socat
        streamcontroller
        tenacity
        thunar
        thunar-archive-plugin
        thunar-media-tags-plugin
        thunar-volman
        wayfreeze
        wl-clipboard
      ];
    };
}
