{ ... }:
{
  env = [
    "ENABLE_HDR_WSI,1"
    "DXVK_HDR,1"
    "ELECTRON_OZONE_PLATFORM_HINT,auto"
    "QT_QPA_PLATFORMTHEME,gtk3"
    "AMD_VULKAND_ICD,RADV"
    "GDK_SCALE,1"
    "QT_SCALE_FACTOR,1"
    "GDK_BACKEND,wayland,x11,*"
    "QT_QPA_PLATFORM,wayland;xcb"
    "CLUTTER_BACKEND,wayland"
    "QT_AUTO_SCREEN_SCALE_FACTOR,1"
    "QT_WAYLAND_DISABLE_WINDOWDECORATION,1"
    "XDG_CURRENT_DESKTOP,Hyprland"
    "XDG_SESSION_TYPE,wayland"
    "XDG_SESSION_DESKTOP,Hyprland"
    "MOZ_ENABLE_WAYLAND,1"
    "EGL_PLATFORM,wayland"
  ];
}
