#!/usr/bin/env bash
# Toggle the Umbriel monitor layout between desktop and work mode.
#
# Umbriel reads ~/.config/umbriel/config.toml and `umbriel msg config-reload`
# re-reads it live. The mode files are generated by home-manager as read-only
# store symlinks; toggling copies the selected one over the live config for
# the rest of the session. A later home-manager switch restores the store
# symlink (desktop mode).
#
# Landscape outputs run dynamic workspaces. A few workspaces are named and
# pinned to outputs, and because names are output-local the mode configs
# re-scope them: STEAM/GAME follow the mode's gaming output (main in desktop
# mode, secondary in work mode), MAIL always lives on the secondary, and
# MEDIA on the portrait. Entering work mode disables the main output, so this
# script moves the STEAM/GAME windows across by name and dumps the remaining
# (anonymous) main-output windows onto the secondary's active workspace.
# Leaving work mode moves STEAM/GAME back to the main output. MAIL and
# anonymous windows are left where they are.
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/umbriel"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/umbriel"
LIVE="$CONFIG_DIR/config.toml"
DESKTOP="$CONFIG_DIR/config-desktop.toml"
WORK="$CONFIG_DIR/config-work.toml"
LAYOUT_ENV="$CONFIG_DIR/layout.env"
MODE_FILE="$STATE_DIR/mode"

USAGE="usage: $0 [desktop|work|toggle]"

umbriel_bin="${UMBRIEL_BIN:-umbriel}"

running() {
  [[ -n "${UMBRIEL_SOCKET:-}" ]] ||
    [[ -S "${XDG_RUNTIME_DIR:-}/umbriel-${WAYLAND_DISPLAY:-}.sock" ]]
}

# Load before taking the snapshot, which needs the monitor names and the list
# of workspaces that follow the gaming output between modes.
if [[ -f "$LAYOUT_ENV" ]]; then
  # shellcheck source=/dev/null
  source "$LAYOUT_ENV"
fi

apply_mode() {
  local src="$1"
  if [[ ! -e "$src" ]]; then
    echo "mode config missing: $src" >&2
    echo 'Install the generated Home Manager configuration first.' >&2
    return 1
  fi

  cp -f --remove-destination "$src" "$LIVE"
}

notify() {
  notify-send "$@" >/dev/null 2>&1 || true
}

mkdir -p "$STATE_DIR"

mode="${1:-}"
if [[ -z "$mode" || "$mode" == "toggle" ]]; then
  if [[ -f "$MODE_FILE" ]] && [[ "$(cat "$MODE_FILE")" == "work" ]]; then
    mode=desktop
  else
    mode=work
  fi
fi

case "$mode" in
desktop | normal)
  mode=desktop
  src="$DESKTOP"
  label="Desktop"
  ;;
work)
  src="$WORK"
  label="Work"
  ;;
*)
  echo "$USAGE" >&2
  exit 1
  ;;
esac

main_out="${UMBRIEL_MAIN_OUT:-}"
secondary_out="${UMBRIEL_SECONDARY_OUT:-}"
named_workspaces="${UMBRIEL_NAMED_WORKSPACES:-}"

in_list() {
  local needle="$1" haystack="$2"
  [[ " $haystack " == *" $needle "* ]]
}

# Snapshot every regular workspace window as id<TAB>workspaceName<TAB>output
# before the reload, while the current mode is still live.
snapshot=""
if running && command -v "$umbriel_bin" >/dev/null 2>&1; then
  wss="$("$umbriel_bin" workspaces --json 2>/dev/null || true)"
  wins="$("$umbriel_bin" windows --json 2>/dev/null || true)"
  if [[ -n "$wss" && -n "$wins" ]]; then
    snapshot="$(
      jq -nr --argjson wss "$wss" --argjson wins "$wins" '
        ( $wss | map({key:.id, value:{name:.name, output:.output}}) | from_entries ) as $ws |
        [ $wins[] |
            select((.scratchpad // "") == "") |
            ($ws[.workspace]) as $wse |
            select($wse != null and $wse.name != "" and $wse.output != "") |
            [ .id, $wse.name, $wse.output ] | @tsv
        ] | .[]
      ' 2>/dev/null || true
    )"
  fi
fi

# Preserve the actual live configuration, including any local edits, for rollback.
backup="$(mktemp "$STATE_DIR/config.XXXXXX")"
trap 'rm -f "$backup"' EXIT
had_live=false
if [[ -e "$LIVE" ]]; then
  cp "$LIVE" "$backup"
  had_live=true
fi

if ! apply_mode "$src"; then
  notify -u critical "Umbriel $label mode" "mode config not installed — run home-manager switch" || true
  exit 1
fi

if ! running || ! command -v "$umbriel_bin" >/dev/null 2>&1; then
  echo "$mode" >"$MODE_FILE"
  notify "$label mode saved" "Umbriel is not running; applied on next session start"
  exit 0
fi

if ! "$umbriel_bin" msg config-reload >/dev/null 2>&1; then
  notify -u critical "Umbriel $label mode" "config-reload failed — restoring the previous mode"
  if [[ "$had_live" == true ]]; then
    cp -f --remove-destination "$backup" "$LIVE"
    "$umbriel_bin" msg config-reload >/dev/null 2>&1 || true
  else
    rm -f "$LIVE"
  fi
  exit 1
fi

echo "$mode" >"$MODE_FILE"

# Wait for the output layout to reflect the new mode before moving windows.
wait_for_outputs() {
  local expected_main=$1 expected_secondary=$2
  local attempts=0
  while [[ $attempts -lt 20 ]]; do
    attempts=$((attempts + 1))
    local outputs
    outputs="$("$umbriel_bin" outputs --json 2>/dev/null || true)"
    if [[ -z "$outputs" ]]; then
      sleep 0.3
      continue
    fi
    local main_ok="true"
    local secondary_ok="true"
    if [[ -n "$main_out" ]]; then
      local main_enabled
      main_enabled=$(jq -r --arg name "$main_out" '.[] | select(.name==$name) | .enabled // false' <<<"$outputs" 2>/dev/null || true)
      main_ok=$([[ "$main_enabled" == "$expected_main" ]] && echo "true" || echo "false")
    fi
    if [[ -n "$secondary_out" ]]; then
      local secondary_enabled
      secondary_enabled=$(jq -r --arg name "$secondary_out" '.[] | select(.name==$name) | .enabled // false' <<<"$outputs" 2>/dev/null || true)
      secondary_ok=$([[ "$secondary_enabled" == "$expected_secondary" ]] && echo "true" || echo "false")
    fi
    if [[ "$main_ok" == "true" ]] && [[ "$secondary_ok" == "true" ]]; then
      return 0
    fi
    sleep 0.2
  done
  return 1
}

# Index of the secondary output's focused workspace, so anonymous windows can
# be dropped onto a real workspace rather than a named one.
active_workspace_index() {
  local out="$1"
  local wss index
  wss="$("$umbriel_bin" workspaces --json 2>/dev/null || true)"
  [[ -n "$wss" ]] || return 1
  index="$(
    jq -r --arg out "$out" '
      [ .[] | select(.output == $out) ] as $w |
      ( ( $w | map(select(.focused // false)) | .[0] ) // ( $w | .[0] ) ) | .index // empty
    ' <<<"$wss" 2>/dev/null || true
  )"
  [[ -n "$index" ]] || return 1
  printf '%s\n' "$index"
}

# Move one window to a workspace selector (bare position or "NAME"/OUTPUT).
# Returns non-zero if the destination is gone or the move is rejected.
move_window() {
  local wid="$1" selector="$2"
  [[ -n "$selector" ]] || return 1
  "$umbriel_bin" msg "window-focus:$wid" >/dev/null 2>&1 &&
    "$umbriel_bin" msg "window-move-to-workspace:$selector" >/dev/null 2>&1
}

moved=0
if [[ -n "$main_out" && -n "$secondary_out" && -n "$snapshot" ]]; then
  if [[ "$mode" == "work" ]]; then
    # Main output disabled: move its windows to the secondary. STEAM/GAME go
    # to the same-named workspace; anonymous windows go to the secondary's
    # active workspace.
    wait_for_outputs false true >/dev/null 2>&1 || true
    anon_pos="$(active_workspace_index "$secondary_out" || true)"
    anon_pos="${anon_pos:-1}"
    while IFS=$'\t' read -r wid wname wout; do
      [[ -n "$wid" && -n "$wname" ]] || continue
      [[ "$wout" == "$main_out" ]] || continue
      if in_list "$wname" "$named_workspaces"; then
        if move_window "$wid" "\"$wname\"/$secondary_out"; then
          moved=$((moved + 1))
        fi
      elif move_window "$wid" "$anon_pos/$secondary_out"; then
        moved=$((moved + 1))
      fi
    done <<<"$snapshot"
  else
    # Main output re-enabled: bring the named workspaces back. MAIL and
    # anonymous windows stay on the secondary.
    wait_for_outputs true true >/dev/null 2>&1 || true
    while IFS=$'\t' read -r wid wname wout; do
      [[ -n "$wid" && -n "$wname" ]] || continue
      [[ "$wout" == "$secondary_out" ]] || continue
      in_list "$wname" "$named_workspaces" || continue
      if move_window "$wid" "\"$wname\"/$main_out"; then
        moved=$((moved + 1))
      fi
    done <<<"$snapshot"
  fi
fi

notify "$label mode" "Monitor layout reloaded"
if [[ $moved -gt 0 ]]; then
  echo "re-homed $moved window(s) to their $label workspaces"
fi
exit 0
