#!/usr/bin/env bash
# Toggle the Umbriel monitor layout between desktop and work mode.
#
# Umbriel reads ~/.config/umbriel/config.toml and `umbriel msg config-reload`
# re-reads it live. The mode files are generated by home-manager as read-only
# store symlinks; toggling copies the selected one over the live config for
# the rest of the session. A later home-manager switch restores the store
# symlink (desktop mode).
#
# Both landscape outputs have local workspaces 1-12. Work mode disables the
# main output. Steam and games are explicitly placed on workspaces 2 and 3
# on the main output in desktop mode, or the secondary output in work mode.
# Other windows keep their current output unless it is being disabled.
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/umbriel"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/umbriel"
LIVE="$CONFIG_DIR/config.toml"
DESKTOP="$CONFIG_DIR/config-desktop.toml"
WORK="$CONFIG_DIR/config-work.toml"
LAYOUT_ENV="$CONFIG_DIR/layout.env"
MODE_FILE="$STATE_DIR/mode"

USAGE="usage: $0 [desktop|work|toggle]"

umbriel_bin="${UMBRIEL_BIN:-umbriel}"

running() {
  [[ -n "${UMBRIEL_SOCKET:-}" ]] ||
    [[ -S "${XDG_RUNTIME_DIR:-}/umbriel-${WAYLAND_DISPLAY:-}.sock" ]]
}

# Load before taking the snapshot, which needs the monitor names.
if [[ -f "$LAYOUT_ENV" ]]; then
  # shellcheck source=/dev/null
  source "$LAYOUT_ENV"
fi

apply_mode() {
  local src="$1"
  if [[ ! -e "$src" ]]; then
    echo "mode config missing: $src" >&2
    echo 'Install the generated Home Manager configuration first.' >&2
    return 1
  fi

  cp -f --remove-destination "$src" "$LIVE"
}

notify() {
  notify-send "$@" >/dev/null 2>&1 || true
}

mkdir -p "$STATE_DIR"

mode="${1:-}"
if [[ -z "$mode" || "$mode" == "toggle" ]]; then
  if [[ -f "$MODE_FILE" ]] && [[ "$(cat "$MODE_FILE")" == "work" ]]; then
    mode=desktop
  else
    mode=work
  fi
fi

case "$mode" in
desktop | normal)
  mode=desktop
  src="$DESKTOP"
  label="Desktop"
  ;;
work)
  src="$WORK"
  label="Work"
  ;;
*)
  echo "$USAGE" >&2
  exit 1
  ;;
esac

# Snapshot windows before disabling an output. Include floating Steam/game
# windows; ordinary floating windows retain their normal reload behavior.
# Rows: id<TAB>destinationName<TAB>oldOutput<TAB>applicationTarget.
snapshot=""
if running && command -v "$umbriel_bin" >/dev/null 2>&1 && [[ -n "${UMBRIEL_MAIN_OUT:-}" ]]; then
  wss="$("$umbriel_bin" workspaces --json 2>/dev/null || true)"
  wins="$("$umbriel_bin" windows --json 2>/dev/null || true)"
  if [[ -n "$wss" && -n "$wins" ]]; then
    snapshot="$(
      jq -nr --argjson wss "$wss" --argjson wins "$wins" '
        ( $wss | map({key:(.id|tostring), value:{name:.name, output:.output}}) | from_entries ) as $ws |
        [ $wins[] |
            select((.scratchpad // "") == "") |
            . as $w |
            (if ((.app_id // "") == "steam" or
                 ((.title // "") | test("Steamwebhelper|Sign in to Steam"))) and
                 (((.title // "") | test("^notificationtoasts"; "i")) | not) then "10"
             elif (((.app_id // "") | test("^(steam_app_.*|gamescope|wow[.]exe)$"; "i")) or
                   ((.title // "") | test("FINAL FANTASY XIV|World of Warcraft|Hytale|[(]DEBUG[)]"; "i"))) and
                  (((.title // "") | test("^Gifts$|^Battle[.]net|^notificationtoasts"; "i")) | not) then "11"
             else "" end) as $appTarget |
            select($appTarget != "" or (.floating // false) != true) |
            ($ws[($w.workspace | tostring)]) as $wse |
            select($wse.name != null and ($appTarget != "" or $wse.name != "13") and ($wse.name != "")) |
            [ $w.id, (if $appTarget != "" then $appTarget else $wse.name end),
              ($wse.output // ""), ($appTarget != "") ] | @tsv
        ] | .[]
      ' 2>/dev/null || true
    )"
  fi
fi

# Preserve the actual live configuration, including any local edits, for rollback.
backup="$(mktemp "$STATE_DIR/config.XXXXXX")"
trap 'rm -f "$backup"' EXIT
had_live=false
if [[ -e "$LIVE" ]]; then
  cp "$LIVE" "$backup"
  had_live=true
fi

if ! apply_mode "$src"; then
  notify -u critical "Umbriel $label mode" "mode config not installed — run home-manager switch" || true
  exit 1
fi

if ! running || ! command -v "$umbriel_bin" >/dev/null 2>&1; then
  echo "$mode" >"$MODE_FILE"
  notify "$label mode saved" "Umbriel is not running; applied on next session start"
  exit 0
fi

if ! "$umbriel_bin" msg config-reload >/dev/null 2>&1; then
  notify -u critical "Umbriel $label mode" "config-reload failed — restoring the previous mode"
  if [[ "$had_live" == true ]]; then
    cp -f --remove-destination "$backup" "$LIVE"
    "$umbriel_bin" msg config-reload >/dev/null 2>&1 || true
  else
    rm -f "$LIVE"
  fi
  exit 1
fi

echo "$mode" >"$MODE_FILE"

# Wait for the new output layout to settle so move-to-workspace sees the
# target outputs in their new role. If this times out the window moves simply
# run against whichever outputs remain available.
wait_for_outputs() {
  local expected_main=$1 expected_secondary=$2
  local attempts=0
  while [[ $attempts -lt 20 ]]; do
    attempts=$((attempts + 1))
    local outputs
    outputs="$("$umbriel_bin" outputs --json 2>/dev/null || true)"
    if [[ -z "$outputs" ]]; then
      sleep 0.3
      continue
    fi
    local main_ok="true"
    local secondary_ok="true"
    if [[ -n "${UMBRIEL_MAIN_OUT:-}" ]]; then
      local main_enabled
      main_enabled=$(jq -r --arg name "$UMBRIEL_MAIN_OUT" '.[] | select(.name==($name|tostring)) | .enabled // false' <<<"$outputs" 2>/dev/null || true)
      main_ok=$([[ "$main_enabled" == "$expected_main" ]] && echo "true" || echo "false")
    fi
    if [[ -n "${UMBRIEL_SECONDARY_OUT:-}" ]]; then
      local secondary_enabled
      secondary_enabled=$(jq -r --arg name "$UMBRIEL_SECONDARY_OUT" '.[] | select(.name==($name|tostring)) | .enabled // false' <<<"$outputs" 2>/dev/null || true)
      secondary_ok=$([[ "$secondary_enabled" == "$expected_secondary" ]] && echo "true" || echo "false")
    fi
    if [[ "$main_ok" == "true" ]] && [[ "$secondary_ok" == "true" ]]; then
      return 0
    fi
    sleep 0.2
  done
  return 1
}

# Place Steam/games explicitly even if they started on the wrong workspace.
# Other windows only move when their output is being disabled.
rehomed=0
desired_main_enabled="false"
desired_secondary_enabled="true"
if [[ "$mode" != "work" ]]; then
  desired_main_enabled="true"
fi
wait_for_outputs "$desired_main_enabled" "$desired_secondary_enabled" >/dev/null 2>&1 || true
if [[ -n "$snapshot" ]]; then
  while IFS=$'\t' read -r wid wname wout app_target; do
    [[ -n "$wid" && -n "$wname" ]] || continue
    dst="$wout"
    if [[ "$app_target" == true ]]; then
      if [[ "$mode" == work ]]; then
        dst="$UMBRIEL_SECONDARY_OUT"
      else
        dst="$UMBRIEL_MAIN_OUT"
      fi
    elif [[ "$mode" == work && "$wout" == "$UMBRIEL_MAIN_OUT" ]]; then
      dst="$UMBRIEL_SECONDARY_OUT"
    fi
    [[ -n "$dst" ]] || continue
    if [[ "$app_target" == true || "$wout" != "$dst" ]]; then
      if "$umbriel_bin" msg "window-focus:$wid" >/dev/null 2>&1 &&
        "$umbriel_bin" msg "window-move-to-workspace:\"$wname\"/$dst" >/dev/null 2>&1; then
        rehomed=$((rehomed + 1))
      fi
    fi
  done <<<"$snapshot"
fi

notify "$label mode" "Monitor layout reloaded"
[[ $rehomed -gt 0 ]] && echo "re-homed $rehomed window(s) to their $label workspaces"
exit 0
