name: build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            substituters = https://cache.nixos.org https://neonvoidx.cachix.org https://nix-community.cachix.org https://cache.garnix.io https://attic.xuyh0120.win/lantian https://hyprland.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= neonvoidx.cachix.org-1:nHFGhvzWqULuNWFbuPwTP0eUW+k7utl0chxXhUJhU1Y= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=

      - name: Set up Cachix
        uses: cachix/cachix-action@v15
        with:
          name: neonvoidx
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Nix flake check
        run: nix flake check -L

      - name: Build void
        run: |
          nix build .#nixosConfigurations.void.config.system.build.toplevel \
            --no-link -L

      - name: Build voidframe
        run: |
          nix build .#nixosConfigurations.voidframe.config.system.build.toplevel \
            --no-link -L
